# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQaTY7F4TgpTLsXdwDrKw1XPDEx0rIva

Iphone Sales Analysis Using Python
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

data = pd.read_csv("/content/apple_products.csv")
print(data.head())

"""##Before moving forward, let’s have a quick look at whether this dataset contains any null values or not:

"""

print(data.isnull().sum())

"""##Now, let’s have a look at the descriptive statistics of the data:"""

print(data.describe())

"""##iPhone Sales Analysis in India🇮🇳 """

high_rated = data.sort_values(by = ["Star Rating"],ascending=False)
high_rated = high_rated.head(10)
print(high_rated['Product Name'])

"""##the number of ratings of the highest-rated iPhones on Flipkart:"""

iphones = high_rated["Product Name"].value_counts()
label = iphones.index
counts = high_rated["Number Of Ratings"]
figure = px.bar(high_rated, x=label,y=counts,title="NO.Of Ratings of high rated iphones ")
figure.show()

"""##the number of reviews of the highest-rated iPhones on Flipkart:"""

iphones = high_rated["Product Name"].value_counts()
label = iphones.index
counts = high_rated["Number Of Reviews"]
figure = px.bar(high_rated, x=label,y=counts,title="NO.Of Reviews of high rated iphones ")
figure.show()

"""##the relationship between the sale price of iPhones and their ratings on Flipkart:"""

figure = px.scatter(data_frame = data, x="Number Of Ratings",
                    y="Sale Price", size="Discount Percentage", 
                    trendline="ols", 
                    title="Relationship between Sale Price and Number of Ratings of iPhones")
figure.show()

"""##the relationship between the discount percentage on iPhones on Flipkart and the number of ratings:"""

figure = px.scatter(data_frame = data, x="Number Of Ratings",
                    y="Discount Percentage", size="Sale Price", 
                    trendline="ols", 
                    title="Relationship between Discount Percentage and Number of Ratings of iPhones")
figure.show()